services:
  - type: web
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_LARAVEL_API_URL
        value: https://task-management-laravel-api.onrender.com/api
      - key: VITE_NODE_API_URL
        value: https://task-management-node-services.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
